import { lazy } from 'react'

export const pages = {
	Home: lazy(() => import('../pages/Home/index.jsx')),
	Home2: lazy(() => import('../widgets/MainContent/home/home2V.jsx')),
	Loader: lazy(() => import('../pages/Loader/index.jsx')),
	ContactUs: lazy(() => import('../pages/ContactUs/index.jsx')),
	Career: lazy(() => import('../pages/Career/index.jsx')),
	Service: lazy(() => import('../pages/Industry/index.jsx')),
	About: lazy(() => import('../pages/About/index.jsx')),
	Blockchain: lazy(() => import('../pages/Blockchain/index.jsx')),
	Token: lazy(() => import('../pages/Token/index.jsx')),
	Metaverse: lazy(() => import('../pages/Metaverse/index.jsx')),
	Blockchain4: lazy(() => import('../pages/Blockchain4/index.jsx')),
	Blockchain6: lazy(() => import('../pages/Blockchain6/index.jsx')),
	Web3: lazy(() => import('../pages/Web3/index.jsx')),
	Wallet: lazy(() => import('../pages/Wallet/index.jsx')),
	Service1: lazy(() => import('../pages/Service_1/index.jsx')),
	ServiceIos: lazy(() => import('../pages/ServiceIOS/index.jsx')),
	WebApp: lazy(() => import('../pages/WebApp/index.jsx')),
	ChatBot: lazy(() => import('../pages/ChatBot/index.jsx')),
	Ai: lazy(() => import('../pages/Ai/index.jsx')),
	AiBlockchain: lazy(() => import('../pages/AiBlockchain/index.jsx')),
	ServiceWeb3: lazy(() => import('../pages/ServiceWeb3/index.jsx')),
	ML: lazy(() => import('../pages/ML/index.jsx')),
	BD: lazy(() => import('../pages/BigData/index.jsx')),
	GD: lazy(() => import('../pages/GD/index.jsx')),
	Motion: lazy(() => import('../pages/Motion/index.jsx')),
	UiUx: lazy(() => import('../pages/UIUX/index.jsx')),
	Copywriting: lazy(() => import('../pages/Copywriting/index.jsx')),
}
