import React, { useEffect, useRef } from 'react'
import { IoIosArrowForward } from 'react-icons/io'
import big from '../../assets/Ai/big.png'
import img11 from '../../assets/Ai/img11.jpg'
import img12 from '../../assets/Ai/img12.jpg'
import img14 from '../../assets/Ai/img14.jpg'
import img15 from '../../assets/Ai/img15.jpg'
import img16 from '../../assets/Ai/img16.jpg'
import img17 from '../../assets/Ai/img17.jpg'
import img18 from '../../assets/Ai/img18.jpg'
import img19 from '../../assets/Ai/img19.jpg'
import img27 from '../../assets/Ai/img27.jpg'
import stick from '../../assets/Ai/stick.png'
import page6 from '../../assets/blockchain6/page6.png'
import { TitleBlockchain } from '../../pages/Blockchain/TitleBlockchain'
import styles from './IndustryAi.module.scss'
const services = [
	{
		title: 'Machine Learning',
		description:
			'We integrate frameworks of machine learning technology in order to make operations of your business "future ready". It will add capabilities such as risk management, real time performance monitoring and enhanced decision making.',
	},
	{
		title: 'Robotics Processing',
		description:
			'Robotics processing is a great tool that allows your human resources to focus on highly valuable tasks. Integrate robotics processing and let AI to handle your repetitive tasks. Focus on what truly matters for your business!',
	},
	{
		title: 'Business Intelligence',
		description:
			'Use power of AI to make smarter decisions for your business! We use complex algorithms that enables our AI to handle and process immense amount of data in real time!',
	},
	{
		title: 'Natural Language Processing',
		description:
			'We develop AI that can interpret and comprehend human language (NLP) effectively. Utilize power of AI with NLP ability to make interactions smoother!',
	},
	{
		title: 'Computer Vision',
		description:
			'AI software enhanced with computer vision can effectively "interpret" images & videos! Utilize AI powered with computer vision to enhance security of your business with enhanced biometric authentication and enjoy other multiple benefits of AI software.',
	},
	{
		title: 'Predictive Analysis',
		description:
			'We develop AI capable of forecasting future outcomes through deep analysis of data, real-time facts and statistics. Our predictive AI enhanced with machine learning (ML) capabilities which allows AI to "learn and provide pinpoint predictions" from past experiences.',
	},
	{
		title: 'GenAI',
		description:
			'Our GenAI (generative AI) capable of generating various types of content. Utilize our GenAI and enjoy various content generated by our AI for personal or business purposes. Types of generated content by our GenAI ranges from simple text to music and writing novels!',
	},
	{
		title: 'Deep Learning',
		description:
			'Enjoy our AI enhanced with "deep learning" functions that utilizes machine learning (ML) with neural networks of multiple layers! It ensures that our AI will effectively and "deeply" learn from data or past experiences & interactions.',
	},
	{
		title: 'Data Science',
		description:
			'Data science is a combination of statistics, data analysis, computer science and domain expertise. It helps to extract valuable insights from raw data which helps to make better decisions and effectively solve specific problems!',
	},
]
const marketPlaceCards = [
	{
		pic: img27,
		title: 'Banking',
		description:
			'AI softwares in banking field helps to automate multiple tasks such as transaction handling, fraud detection, receipt generation and customer service.',
	},
	{
		pic: img12,
		title: 'Healthcare',
		description:
			'AI software in healthcare field helps with data gathering, storing, analyzing, customer services and even personalized care through ML/NLP/deep learn capabilities.',
	},
	{
		pic: img11,
		title: 'Real estate',
		description:
			'Businesses in real estate sector can benefit from AI softwares in multiple perspectives such as assistance in documentation, guidelines, customer background analysis and even lead generation through meaningful interactions.',
	},
	{
		pic: img14,
		title: 'Travel & Tourism',
		description:
			'Businesses in travel & tourism sector can benefit from outstanding features of AI such as customized itineraries, flight & hotel bookings, price analytics & comparison and many other.',
	},
	{
		pic: img15,
		title: 'Telecommunication',
		description:
			'With our NLP/ML AI solutions, the telecommunications sector can benefit from 24/7 active customer service without need of human resources. AI will make sure to maintain meaningful interactions with clients.',
	},
	{
		pic: img16,
		title: 'Food industry',
		description:
			'Businesses in food industry can benefit from AI in many ways such as inventory management, data entry, storing, analysis and back end office tasks automation.',
	},
	{
		pic: img17,
		title: 'Creative & Art',
		description:
			'Businesses in creative & art industry can benefit from AI features such as video & image editing, voice changer and creative advises & ideas generation to boost creativity.',
	},
	{
		pic: img18,
		title: 'HR & Recruitment',
		description:
			'HR industry can benefit from AI in multiple ways such as scheduling interviews, candidate background analysis and evaluation of results.',
	},
	{
		pic: img19,
		title: 'Education',
		description: `Education industry can benefit from outstanding AI features such as customized learning, custom study materials generation that fits individual student's learning patterns and setting up exams & evaluation of scores.`,
	},
]

const IndustryAi = () => {
	const serviceRefs = useRef([])

	useEffect(() => {
		const observer = new IntersectionObserver(
			entries => {
				entries.forEach(entry => {
					if (entry.isIntersecting) {
						const index = serviceRefs.current.indexOf(entry.target)
						if (index !== -1) {
							setTimeout(() => {
								entry.target.classList.add(styles.fadeIn)
							}, index * 300)
						}
						observer.unobserve(entry.target)
					}
				})
			},
			{ threshold: 0.1 }
		)

		serviceRefs.current.forEach(ref => ref && observer.observe(ref))

		return () => observer.disconnect()
	}, [])

	return (
		<>
			<div className={styles.container}>
				<h2>Our Extensive AI Domain Expertise</h2>
				<p className={styles.description}>
					We carefully monitor the global technological advancements in order to
					utilize the knowledge to construct AI tools & models with great
					performace.
				</p>
				<div className={styles.servicesGrid}>
					{services.map((service, index) => (
						<div
							key={index}
							className={`${styles.serviceCard}`}
							ref={el => (serviceRefs.current[index] = el)}
						>
							<div className={styles.borderTop}></div>
							<h3>{service.title}</h3>
							<p>{service.description}</p>
						</div>
					))}
				</div>
			</div>
			<h2 style={{ paddingLeft: '50px', paddingRight: '50px' }}>
				AI DEVELOPMENT PROCESSES: BRINGING YOUR IDEAS TO LIFE
			</h2>
			<p style={{ paddingLeft: '50px', paddingRight: '50px' }}>
				We use result-driven AI development approach where we ensure the high
				quality and effective functionality of our AI software! Our team of
				expert software engineers carefully analyzes the clients' development
				requirements where we make sure to create AI solutions that will
				perfectly match their needs.
			</p>

			<div className={styles.frame}>
				<div className={styles.header}>
					<img src={big} alt='' />
				</div>
				<div className={styles.service}>
					<div className={styles.items}>
						<div className={styles.frameTitle}>
							<img src={stick} alt='' /> <p>Project Consultation</p>
						</div>
						<br />
						<br />
						<div className={styles.itemsContent}>
							<p>
								Our team will organize free consultation call where we discuss
								requirements for AI software development
							</p>
						</div>
					</div>
					<div className={styles.items}>
						<div className={styles.frameTitle}>
							<img src={stick} alt='' /> <p>Project Planning</p>
						</div>
						<div className={styles.itemsContent}>
							<p>
								After deep analysis, our team proceeds with project development
								roadmap where we compose a software that aligns with desired
								outcomes
							</p>
						</div>
					</div>
					<div className={styles.items}>
						<div className={styles.frameTitle}>
							<img src={stick} alt='' /> <p>Quality Testing</p>
						</div>
						<div className={styles.itemsContent}>
							<p>
								Our software undergoes intensive testing where we make sure that
								software performs flawlessly and error-free.
							</p>
						</div>
					</div>
					<div className={styles.items}>
						<div className={styles.frameTitle}>
							<img src={stick} alt='' /> <p>Project Analysis</p>
						</div>
						<div className={styles.itemsContent}>
							<p>
								Before our team proceeds with AI software development plan
								draft, we carefully analyse clients' business needs and
								requirements
							</p>
						</div>
					</div>
					<div className={styles.items}>
						<div className={styles.frameTitle}>
							<img src={stick} alt='' /> <p>Project Development</p>
						</div>
						<div className={styles.itemsContent}>
							<p>
								At Jussplay, we strictly follow the deadlines and clients' needs
								in order to build software that exceeds expectations
							</p>
						</div>
					</div>
					<div className={styles.items}>
						<div className={styles.frameTitle}>
							<img src={stick} alt='' /> <p>Maintenance & Support</p>
						</div>
						<div className={styles.itemsContent}>
							<p>
								At Jussplay, we care about our clients' satisfaction in a long
								term. We ensure affordable maintenance & support for our AI
								softwares in order to sustain its smooth functioning.
							</p>
						</div>
					</div>
				</div>
			</div>

			<div className={styles.marketplaceContainer}>
				<TitleBlockchain
					title={`Benefits of AI software for industries of any size`}
					subTitle={`Our aim is to build outstanding AI software that will assist businesses across their automation journey and multiply their efficiency. We build custom AI software that can perfectly fit into any industry of your choice.`}
				/>
				<div className={styles.marketplaceCards}>
					{marketPlaceCards.map((card, index) => (
						<div key={index} className={styles.marketplaceCard}>
							<div className={styles.cardIcon}>
								<img src={card.pic} alt='' />
							</div>
							<h3 className={styles.cardTitle}>{card.title}</h3>
							<p className={styles.cardDescription}>{card.description}</p>
						</div>
					))}
				</div>
			</div>
			<section className={styles.bannerSection}>
				<div className={styles.container2}>
					<div className={styles.imageWrapper}>
						<img src={page6} className={styles.image} />
					</div>
					<div className={styles.content}>
						<h2 className={styles.title}>
							Connect with us for a free consultation about your AI based
							business project
						</h2>
						<p className={styles.description}>
							We offer extremely affordable and flexible prices for our AI
							solutions. Connect with our team of experts through free
							consultation call to discuss about your dream AI project!
						</p>
						{/* <ul className={styles.featuresList}>
							<li>Binance exchange clone</li>
							<li>Coinbase exchange clone</li>
						</ul> */}
						<button className={styles.meetButton}>
							Meet with us <IoIosArrowForward />
						</button>
					</div>
				</div>
			</section>
		</>
	)
}

export default IndustryAi
