name: CI and Deploy Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint-and-typecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install --immutable

    deploy:
        runs-on: ubuntu-latest
        needs: lint-and-typecheck
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21'

            - name: Install Dependencies
              run: npm install

            - name: Build Frontend
              run: npm run build

            - name: Deploy to VPS
              env:
                  VPS_HOST: ${{ secrets.VPS_HOST }}
                  VPS_USER: ${{ secrets.VPS_USER }}
                  VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
                  FRONTEND_PATH: ${{ secrets.APP_PATH }}
              run: |
                  echo "$VPS_SSH_KEY" > deploy_key
                  chmod 600 deploy_key
                  rsync -avz --delete -e "ssh -i deploy_key -o StrictHostKeyChecking=no" \
                    ./dist/ $VPS_USER@$VPS_HOST:$FRONTEND_PATH
                  ssh -i deploy_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
                    sudo systemctl restart nginx
                  EOF
                  rm deploy_key
